version = 0.1
[default.deploy.parameters]
stack_name = "layered-blog"
resolve_s3 = true
s3_prefix = "layered-blog"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "Prefix=\"blog\" DocDBIdentifier=\"docdb-2023-07-31-13-17-47\" DocDBUsername=\"catalinadelacuesta\" DocDBVPCSubnet=\"subnet-3295bd1c\" DocDBSecurityGroup=\"sg-5ac6ac05\""
